color: null
fieldLayouts:
  d092aa86-8465-4cd5-8504-8c203781e997:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-04T17:57:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7647c052-d9d4-4d3e-ab3c-9cd5d2431a2d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T18:03:07+00:00'
            elementCondition: null
            fieldUid: b98fec3c-d4ba-4e3d-93ac-ec92c32b4715 # Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4c5f3ca-91e7-4cdf-b7f0-a8934eb588bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T18:03:07+00:00'
            elementCondition: null
            fieldUid: cf204739-4863-4c56-92f9-dbbb551bc806 # Price (Hero, Large or Single)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 507fac49-16c6-4438-b7e2-e95aa360f30e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T18:03:07+00:00'
            elementCondition: null
            fieldUid: b2cddd31-9ff2-4853-b99a-ca30c543baf4 # Price (bagel)
            handle: null
            includeInCards: false
            instructions: 'Medium size items and bagel sandwiches.'
            label: 'Price (Bagel or Medium)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3aedba5-c66f-4879-9dd4-990b106a7fb1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T18:03:07+00:00'
            elementCondition: null
            fieldUid: 909ed758-b171-4ffe-a88f-590a4646fc3d # Price (roll)
            handle: null
            includeInCards: false
            instructions: 'Use for sandwiches on a roll or Small items.'
            label: 'Price (Roll or Small)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e28e4f20-7253-4f50-8f91-f0417b12e25f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62d9a5fa-5c98-4c15-b7f6-8a23306544c7
        userCondition: null
handle: menuItem
hasTitleField: true
icon: pot-food
name: 'Menu Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
