color: blue
fieldLayouts:
  d5bbedaa-8cce-40c1-8170-8623174e7f35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-01T17:50:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6e21d29c-df12-4a7c-8419-e0ca61b6014d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-01T17:52:36+00:00'
            elementCondition: null
            fieldUid: cb6bdfcf-f7b2-40dd-a5a8-adc0eb8dd464 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90f56433-e73e-4100-aa2a-6b44d8aba51f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e84679b1-8672-4d71-9e4f-00e85a95a7f0
        userCondition: null
handle: menuSection
hasTitleField: true
icon: paragraph
name: 'Menu Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
