color: null
fieldLayouts:
  832f3ee2-397f-4be2-bf65-a82b1ee01ac9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-07T21:29:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b802a769-c667-4227-b61d-531ac0b46e46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T21:50:01+00:00'
            elementCondition: null
            fieldUid: 98999f18-3843-49f8-85e5-2ca9318e973a # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9ca9226-3b82-4db2-8021-2232938c81a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T00:15:37+00:00'
            elementCondition: null
            fieldUid: eb8b1d14-8f3c-413a-8833-a9121228b253 # Blurb
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c58edc33-344f-43aa-b9cb-c110829dee5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 130b7ee9-557d-41af-9bc2-8df8c73d240d
        userCondition: null
handle: triptych
hasTitleField: true
icon: ''
name: Triptych
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
