altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ccc9359c-968f-4630-a257-f111ba51e3d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-04T22:22:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9168da5c-0b1f-4f2f-a40e-dc1a34b00055
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2b0c8274-5623-403a-ab9a-8c27ed8de7d7
        userCondition: null
fs: assets
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
