columnSuffix: null
handle: menuItem
instructions: null
name: 'Menu Item'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 37df55ab-8d7b-4469-946d-ca021cba6779 # Menu Item
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
