dateModified: 1730483890
email:
  fromEmail: fultonchain@gmail.com
  fromName: '7 Days Deli'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0e38a1fc-ee6d-486a-af18-314caecb2a9c: 'Menu Section' # Menu Section
    9beb901b-f768-410d-837b-8b81f19768d3: '7 Days Deli' # 7 Days Deli
    74d68e85-fc57-4d6a-8266-8593bfafe4fb: 'Menu Section' # Menu Section
    a9c14982-f200-4896-abb1-79eeae7c2649: Menu # Menu
    b03afd44-8426-4eeb-adb6-47b908e1ad1f: '7 Days Deli' # 7 Days Deli
    cb6bdfcf-f7b2-40dd-a5a8-adc0eb8dd464: 'Rich Text' # Rich Text
    dd36437f-2cfc-40ed-8dbd-159ac519a24e: 'Rich Text' # Rich Text
    e45c4ec0-5b9b-4c13-9342-7186a53c0392: Simple # Simple
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: '7 Days Deli'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
