dateModified: 1730410371
email:
  fromEmail: fultonchain@gmail.com
  fromName: '7 Days Deli'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    9beb901b-f768-410d-837b-8b81f19768d3: '7 Days Deli' # 7 Days Deli
    b03afd44-8426-4eeb-adb6-47b908e1ad1f: '7 Days Deli' # 7 Days Deli
system:
  edition: solo
  live: true
  name: '7 Days Deli'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
