defaultPlacement: beginning
enableVersioning: true
entryTypes:
  -
    uid: 74d68e85-fc57-4d6a-8266-8593bfafe4fb # Menu Section
handle: menuSection
maxAuthors: 1
minAuthors: 1
name: 'Menu Section'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  9beb901b-f768-410d-837b-8b81f19768d3: # 7 Days Deli
    enabledByDefault: true
    hasUrls: true
    template: menu/_entry.twig
    uriFormat: 'menu/{slug}'
structure:
  maxLevels: null
  uid: 7facc492-a196-4a09-b6a3-bc8289aa98aa
type: structure
